import type { ComponentEntry } from './types'

export const jitterTsiEntries: ComponentEntry[] = [
  {
    id: 'jitter-product-navigation', title: 'Product Navigation', site: 'jitter', category: 'Navigation', loadComponent: () => import('../library/jitter/ProductNavigation.vue'),
    summary: '提取 Jitter 产品菜单、分类导航和行动入口，支持键盘关闭、窄屏菜单及可配置导航列表。', tags: ['Navigation', 'Dropdown', 'Responsive'],
    source: 'jitter.video/src/App.vue (.site-header, .desktop-nav, .nav-dropdown, .mobile-nav); jitter.video/src/style.css', sourceKind: 'adapted',
    files: ['library/jitter/ProductNavigation.vue'], assets: ['/assets/jitter/jitter.svg', '/assets/jitter/lausanne-400.woff2'],
    usage: `<script setup lang="ts">\nimport ProductNavigation from './library/jitter/ProductNavigation.vue'\nfunction navigate(target: string) { console.info('Navigate:', target) }\nfunction start() { console.info('Start selected') }\n</script>\n<template>\n  <ProductNavigation active="Templates" cta="Try for free" :default-open="true" @navigate="navigate" @start="start" />\n</template>`,
    props: [
      { name: 'cta', label: '行动按钮', type: 'text', default: 'Try for free', description: '触发 start 事件；links 和 products 数组可在代码中传入导航项目。' },
      { name: 'active', label: '当前导航', type: 'select', default: 'Templates', options: ['Templates', 'Pricing'], description: '按导航项目 label 标记当前页面。' },
      { name: 'defaultOpen', label: '展开产品菜单', type: 'boolean', default: true, description: '桌面菜单初始状态；移动端通过菜单按钮打开全部项目。' },
    ], background: '#f4f2f7', foreground: '#19181b',
  },
  {
    id: 'jitter-pricing-plans', title: 'Pricing Plans', site: 'jitter', category: 'Commerce', loadComponent: () => import('../library/jitter/PricingPlans.vue'),
    summary: '将 Jitter 定价页抽为可配置套餐组，月付与年付同步切换，选择事件包含套餐对象和计费周期。', tags: ['Pricing', 'Billing', 'Plans'],
    source: 'jitter.video/src/components/HomePage.vue:26 (plans); HomePage.vue:81 (.pricing-grid, .billing-toggle); jitter.video/src/style.css', sourceKind: 'adapted',
    files: ['library/jitter/PricingPlans.vue'], assets: ['/assets/jitter/lausanne-400.woff2'],
    usage: `<script setup lang="ts">\nimport PricingPlans, { type MotionPlan } from './library/jitter/PricingPlans.vue'\nfunction select(plan: MotionPlan, yearly: boolean) { console.info(plan.id, yearly) }\n</script>\n<template>\n  <PricingPlans title="Find your flow." :yearly="true" currency="$" @select="select" />\n</template>`,
    props: [
      { name: 'title', label: '标题', type: 'text', default: 'Find your flow.', description: '可通过 plans 数组传入真实套餐及特性；默认数据源于本地演示站。' },
      { name: 'yearly', label: '按年计费', type: 'boolean', default: true, description: '更新后同步计费状态；用户切换触发 billing-change。' },
      { name: 'currency', label: '货币符号', type: 'text', default: '$', description: '价格前缀；价格数字来自 plans，不连接付费服务。' },
    ], background: '#fff', foreground: '#19181b',
  },
  {
    id: 'jitter-template-browser', title: 'Template Browser', site: 'jitter', category: 'Media', loadComponent: () => import('../library/jitter/TemplateBrowser.vue'),
    summary: '提取模板库的分类、搜索和作品列表，使用原视频真实帧，筛选结果与空状态可直接复用。', tags: ['Gallery', 'Filter', 'Search'],
    source: 'jitter.video/src/components/HomePage.vue:77 (.library-tools, .library-grid); jitter.video/src/state.ts (templates); public/assets/template-{1,5,6}.mp4', sourceKind: 'adapted',
    files: ['library/jitter/TemplateBrowser.vue'], assets: ['/assets/jitter/lausanne-400.woff2', '/assets/jitter/template-1-poster.jpg', '/assets/jitter/template-5-poster.jpg', '/assets/jitter/template-6-poster.jpg'],
    usage: `<script setup lang="ts">\nimport TemplateBrowser, { type MotionTemplate } from './library/jitter/TemplateBrowser.vue'\nfunction select(item: MotionTemplate) { console.info('Open template:', item.id) }\n</script>\n<template>\n  <TemplateBrowser :show-search="true" @select="select" />\n</template>`,
    props: [
      { name: 'title', label: '标题', type: 'text', default: 'Made to make your own.', description: '通过 items 数组自定义作品；分类由 items 自动生成。' },
      { name: 'showSearch', label: '显示搜索', type: 'boolean', default: true, description: '按作品名称与类别搜索；选择作品触发 select(item)。' },
    ], background: '#fff', foreground: '#19181b',
  },
  {
    id: 'jitter-faq-list', title: 'FAQ List', site: 'jitter', category: 'Typography', loadComponent: () => import('../library/jitter/FaqList.vue'),
    summary: '提取 Jitter FAQ 的分栏标题、细线和展开按钮，问答列表、默认展开项与 change 事件独立封装。', tags: ['FAQ', 'Disclosure', 'Content'],
    source: 'jitter.video/src/components/HomePage.vue:20 (faqs); HomePage.vue:73 (.faq-section); jitter.video/src/style.css (.faq-item)', sourceKind: 'adapted',
    files: ['library/jitter/FaqList.vue'], assets: ['/assets/jitter/lausanne-400.woff2'],
    usage: `<script setup lang="ts">\nimport FaqList from './library/jitter/FaqList.vue'\nconst items = [{ question: 'Can I start for free?', answer: 'Yes, choose a template and start creating.' }, { question: 'Can I customize the result?', answer: 'All content can be configured by the host application.' }]\n</script>\n<template>\n  <FaqList :items="items" :initial-open="0" />\n</template>`,
    props: [
      { name: 'title', label: '问答标题', type: 'text', default: 'A few good questions.', description: 'items 数组包含 question 与 answer，可在集成代码中配置。' },
      { name: 'initialOpen', label: '展开项', type: 'number', default: 0, min: -1, max: 3, step: 1, description: '从 0 开始；-1 全部收起。展开或关闭触发 change(index|null)。' },
    ], background: '#fff', foreground: '#19181b',
  },
  {
    id: 'tsi-recognition-carousel', title: 'Recognition Carousel', site: '21tsi', category: 'Typography', loadComponent: () => import('../library/tsi/RecognitionCarousel.vue'),
    summary: '将 21TSI 滚动业绩展示改为独立可控轮播，保留大型轻字重数字、分段进度与键盘切换。', tags: ['Metrics', 'Carousel', 'Tabs'],
    source: '21tsi.com/index.html:246 (.recognition_titles, .recognition_nav); 21tsi.com/public/assets/styles/main.css', sourceKind: 'adapted',
    files: ['library/tsi/RecognitionCarousel.vue'], assets: ['/assets/tsi/SaansVF.woff2'],
    usage: `<script setup lang="ts">\nimport RecognitionCarousel from './library/tsi/RecognitionCarousel.vue'\nconst items = [{ label: 'Global Revenue', headline: 'Over 40M', detail: 'Bootstrapped without external investments.' }, { label: 'Customer Base', headline: '100k customers', detail: 'A growing global community.' }]\n</script>\n<template>\n  <RecognitionCarousel :items="items" :initial-index="0" @change="index => console.info(index)" />\n</template>`,
    props: [
      { name: 'eyebrow', label: '章节名称', type: 'text', default: 'Recognition', description: '业绩内容可通过 items 数组配置 label、headline 与 detail。' },
      { name: 'initialIndex', label: '当前业绩', type: 'number', default: 0, min: 0, max: 2, step: 1, description: '更新后同步当前项；支持左右方向键、Home、End 和前后按钮。' },
    ], background: '#101913', foreground: '#f8f8f6',
  },
  {
    id: 'tsi-brand-portfolio', title: 'Brand Portfolio', site: '21tsi', category: 'Navigation', loadComponent: () => import('../library/tsi/BrandPortfolio.vue'),
    summary: '将 21TSI 的品牌文字与标志展示整理为品牌选择器，本地四品牌标志与列表选择状态保持同步。', tags: ['Portfolio', 'Brands', 'Selection'],
    source: '21tsi.com/index.html:263 (.recognition_title--brands); index.html:308 (.recognition_brands_cartouche); public/assets/images/brands/*.svg', sourceKind: 'adapted',
    files: ['library/tsi/BrandPortfolio.vue'], assets: ['/assets/tsi/SaansVF.woff2', '/assets/tsi/maddle.svg', '/assets/tsi/mw.svg', '/assets/tsi/ascend.svg', '/assets/tsi/nordik.svg'],
    usage: `<script setup lang="ts">\nimport BrandPortfolio, { type PortfolioBrand } from './library/tsi/BrandPortfolio.vue'\nfunction openBrand(brand: PortfolioBrand) { console.info('Selected brand:', brand.id) }\n</script>\n<template>\n  <BrandPortfolio :initial-index="0" @select="openBrand" />\n</template>`,
    props: [
      { name: 'title', label: '标题', type: 'text', default: 'A collective ambition.', description: 'brands 数组支持 id、name、logo、category、description；默认文案为展示摘要。' },
      { name: 'initialIndex', label: '当前品牌', type: 'number', default: 0, min: 0, max: 3, step: 1, description: '按数组序号选择；切换触发 change(brand)，入口触发 select(brand)。' },
      { name: 'cta', label: '品牌入口', type: 'text', default: 'Explore brand', description: '仅发出选择事件，由宿主提供真实品牌导航行为。' },
    ], background: '#171b18', foreground: '#f4f5f3',
  },
  {
    id: 'jitter-motion-tile', title: 'Motion Tile', site: 'jitter', category: 'Media',
    summary: '保留 Jitter 动态作品卡的影像、作者标记和留白，支持视口感知播放、暂停、重试与选择事件。',
    tags: ['Video', 'Autoplay', 'Showcase'],
    source: 'jitter.video/src/components/VideoTile.vue; jitter.video/src/components/HomePage.vue (.showcase-card); jitter.video/src/style.css (.showcase-caption)',
    sourceKind: 'extracted', loadComponent: () => import('../library/jitter/MotionTile.vue'),
    files: ['library/jitter/MotionTile.vue'],
    assets: ['/assets/jitter/template-5.mp4', '/assets/jitter/template-5-poster.jpg', '/assets/jitter/lausanne-400.woff2', '/assets/jitter/lausanne-600.woff2'],
    usage: `<script setup lang="ts">\nimport MotionTile from './library/jitter/MotionTile.vue'\n\nfunction openTemplate() {\n  console.info('Template selected')\n}\n</script>\n\n<template>\n  <MotionTile title="Stretched Type Repeater" author="Jitter" :autoplay="true" @select="openTemplate" />\n</template>`,
    props: [
      { name: 'title', label: '作品名称', type: 'text', default: 'Stretched Type Repeater', description: '作品标题，同时用于视频与选择按钮的无障碍名称。' },
      { name: 'author', label: '作者', type: 'text', default: 'Jitter', description: '作者名称，首字母自动生成头像。' },
      { name: 'autoplay', label: '自动播放', type: 'boolean', default: true, description: '进入视口后静音播放，遵循系统减少动态效果设置。' },
      { name: 'loop', label: '循环播放', type: 'boolean', default: true, description: '视频播放结束后是否循环。' },
      { name: 'source', label: '视频地址', type: 'text', default: '/assets/jitter/template-5.mp4', description: 'MP4 地址；默认资源随组件下载。' },
      { name: 'poster', label: '静态封面', type: 'text', default: '/assets/jitter/template-5-poster.jpg', description: '暂停或减少动态效果时显示的封面，默认从原视频提取。' },
    ], background: '#f2f0f4', foreground: '#19181b',
  },
  {
    id: 'jitter-motion-timeline', title: 'Motion Timeline', site: 'jitter', category: 'Media',
    summary: '从 Jitter 编辑器中抽象出的动效画板与时间轴，播放、暂停、重置和时间拖动保持同步。',
    tags: ['Timeline', 'Motion', 'Interactive'],
    source: 'jitter.video/src/components/WorkspacePage.vue (.editor-timeline, .editable-artboard); jitter.video/src/style.css (.timeline-track, .timeline-clip)',
    sourceKind: 'adapted', loadComponent: () => import('../library/jitter/MotionTimeline.vue'),
    files: ['library/jitter/MotionTimeline.vue'], assets: ['/assets/jitter/lausanne-400.woff2', '/assets/jitter/lausanne-800.woff2'],
    usage: `<script setup lang="ts">\nimport MotionTimeline from './library/jitter/MotionTimeline.vue'\n</script>\n\n<template>\n  <MotionTimeline title="Make it move." :duration="4" color="#b498f5" :autoplay="true" />\n</template>`,
    props: [
      { name: 'title', label: '画板文字', type: 'text', default: 'Make it move.', description: '动效画板中呈现的标题。' },
      { name: 'duration', label: '时长', type: 'number', default: 4, min: 0.5, max: 30, step: 0.5, description: '动效时长，单位为秒；范围为 0.5 至 30。' },
      { name: 'color', label: '画板背景', type: 'color', default: '#b498f5', description: '画板背景色。' },
      { name: 'autoplay', label: '自动播放', type: 'boolean', default: true, description: '自动播放动效；系统减少动态效果时默认暂停。' },
    ], background: '#edebef', foreground: '#19181b',
  },
  {
    id: 'tsi-focus-accordion', title: 'Focus Accordion', site: '21tsi', category: 'Navigation',
    summary: '提取 21TSI 的章节编号、细线分隔和轻量字体，将 Our Focus 内容整理为可访问的图文折叠组件。',
    tags: ['Accordion', 'Editorial', 'Image'],
    source: '21tsi.com/index.html:442 (.sphereFocus, .collapse--cols); 21tsi.com/public/assets/styles/main.css (.collapse_title, .collapse_content)',
    sourceKind: 'adapted', loadComponent: () => import('../library/tsi/FocusAccordion.vue'),
    files: ['library/tsi/FocusAccordion.vue'],
    assets: ['/assets/tsi/SaansVF.woff2', '/assets/tsi/focus-1.webp', '/assets/tsi/focus-2.webp', '/assets/tsi/focus-3.webp', '/assets/tsi/focus-4.webp'],
    usage: `<script setup lang="ts">\nimport FocusAccordion from './library/tsi/FocusAccordion.vue'\n</script>\n\n<template>\n  <FocusAccordion title="Our Focus" :default-open="0" :show-image="true" @change="index => console.info('Open item:', index)" />\n</template>`,
    props: [
      { name: 'title', label: '章节标题', type: 'text', default: 'Our Focus', description: '组件标题；items 数组可在代码中传入自定义内容与图片。' },
      { name: 'defaultOpen', label: '展开项', type: 'number', default: 0, min: -1, max: 3, step: 1, description: '从 0 开始的展开项序号；-1 表示全部收起；更新此值会同步展开状态。' },
      { name: 'showImage', label: '显示图片', type: 'boolean', default: true, description: '是否显示当前展开项对应的本地图片。' },
    ], background: '#101913', foreground: '#f1f3f2',
  },
  {
    id: 'tsi-progress-navigation', title: 'Progress Navigation', site: '21tsi', category: 'Navigation',
    summary: '沿用 21TSI 导航的单色标志、圆点与章节进度线，支持导航切换、移动端菜单和联系事件。',
    tags: ['Navigation', 'Progress', 'Responsive'],
    source: '21tsi.com/index.html:73 (.navbar, .navbar_progress); 21tsi.com/public/assets/styles/main.css (.navbar_main, .navbar_nav_link, .button)',
    sourceKind: 'adapted', loadComponent: () => import('../library/tsi/ProgressNavigation.vue'),
    files: ['library/tsi/ProgressNavigation.vue'], assets: ['/assets/tsi/SaansVF.woff2', '/assets/tsi/logo-small.svg'],
    usage: `<script setup lang="ts">\nimport ProgressNavigation from './library/tsi/ProgressNavigation.vue'\n</script>\n\n<template>\n  <ProgressNavigation :active-index="0" contact-label="Contact" @navigate="index => console.info('Section:', index)" @contact="console.info('Contact selected')" />\n</template>`,
    props: [
      { name: 'activeIndex', label: '选中章节', type: 'number', default: 0, min: 0, max: 2, step: 1, description: '从 0 开始的章节序号；更新此值会同步导航状态。items 可在代码中自定义。' },
      { name: 'contactLabel', label: '联系按钮', type: 'text', default: 'Contact', description: '桌面端联系按钮文字。' },
      { name: 'showContact', label: '显示联系入口', type: 'boolean', default: true, description: '宽屏时显示联系入口；紧凑视图显示菜单按钮。' },
    ], background: '#101211', foreground: '#f8f8f6',
  },
]
