// Generated from https://wise.com/zh-hk/ by scripts/sync-wise-data.mjs.
// Keep this snapshot in source control so the calculator still works offline.

export const wiseSourceCurrencies = [
  {
    "code": "EUR",
    "name": "欧元",
    "popular": true
  },
  {
    "code": "GBP",
    "name": "英镑",
    "popular": false
  },
  {
    "code": "USD",
    "name": "美元",
    "popular": true
  },
  {
    "code": "AED",
    "name": "阿联酋迪拉姆",
    "popular": false
  },
  {
    "code": "ARS",
    "name": "阿根廷比索",
    "popular": false
  },
  {
    "code": "AUD",
    "name": "澳元",
    "popular": false
  },
  {
    "code": "BRL",
    "name": "巴西雷亚尔",
    "popular": false
  },
  {
    "code": "CAD",
    "name": "加拿大元",
    "popular": false
  },
  {
    "code": "CHF",
    "name": "瑞士法郎",
    "popular": false
  },
  {
    "code": "CLP",
    "name": "智利比索",
    "popular": false
  },
  {
    "code": "CNY",
    "name": "人民币",
    "popular": false
  },
  {
    "code": "CZK",
    "name": "捷克克朗",
    "popular": false
  },
  {
    "code": "DKK",
    "name": "丹麦克朗",
    "popular": false
  },
  {
    "code": "GEL",
    "name": "格鲁吉亚拉里",
    "popular": false
  },
  {
    "code": "HKD",
    "name": "港币",
    "popular": true
  },
  {
    "code": "HUF",
    "name": "匈牙利福林",
    "popular": false
  },
  {
    "code": "IDR",
    "name": "印尼盾",
    "popular": false
  },
  {
    "code": "ILS",
    "name": "以色列新谢克尔",
    "popular": false
  },
  {
    "code": "INR",
    "name": "印度卢比",
    "popular": false
  },
  {
    "code": "JPY",
    "name": "日元",
    "popular": false
  },
  {
    "code": "MXN",
    "name": "墨西哥比索",
    "popular": false
  },
  {
    "code": "MYR",
    "name": "马来西亚林吉特",
    "popular": false
  },
  {
    "code": "NOK",
    "name": "挪威克朗",
    "popular": false
  },
  {
    "code": "NZD",
    "name": "新西兰元",
    "popular": false
  },
  {
    "code": "PHP",
    "name": "菲律宾比索",
    "popular": false
  },
  {
    "code": "PLN",
    "name": "波兰兹罗提",
    "popular": false
  },
  {
    "code": "RON",
    "name": "罗马尼亚列伊",
    "popular": false
  },
  {
    "code": "SEK",
    "name": "瑞典克朗",
    "popular": false
  },
  {
    "code": "SGD",
    "name": "新加坡元",
    "popular": false
  },
  {
    "code": "THB",
    "name": "泰铢",
    "popular": false
  },
  {
    "code": "TRY",
    "name": "土耳其里拉",
    "popular": false
  },
  {
    "code": "UAH",
    "name": "乌克兰格里夫纳",
    "popular": false
  }
] as const

export const wiseTargetCurrencies = [
  {
    "code": "EUR",
    "name": "欧元",
    "popular": true
  },
  {
    "code": "USD",
    "name": "美元",
    "popular": true
  },
  {
    "code": "GBP",
    "name": "英镑",
    "popular": true
  },
  {
    "code": "AED",
    "name": "阿联酋迪拉姆",
    "popular": false
  },
  {
    "code": "ALL",
    "name": "阿尔巴尼亚列克",
    "popular": false
  },
  {
    "code": "AMD",
    "name": "亚美尼亚德拉姆",
    "popular": false
  },
  {
    "code": "ARS",
    "name": "阿根廷比索",
    "popular": false
  },
  {
    "code": "AUD",
    "name": "澳元",
    "popular": false
  },
  {
    "code": "AZN",
    "name": "阿塞拜疆马纳特",
    "popular": false
  },
  {
    "code": "BBD",
    "name": "巴巴多斯元",
    "popular": false
  },
  {
    "code": "BDT",
    "name": "孟加拉塔卡",
    "popular": false
  },
  {
    "code": "BHD",
    "name": "巴林第纳尔",
    "popular": false
  },
  {
    "code": "BMD",
    "name": "百慕大元",
    "popular": false
  },
  {
    "code": "BND",
    "name": "文莱元",
    "popular": false
  },
  {
    "code": "BOB",
    "name": "玻利维亚玻利维亚诺",
    "popular": false
  },
  {
    "code": "BRL",
    "name": "巴西雷亚尔",
    "popular": false
  },
  {
    "code": "BSD",
    "name": "巴哈马元",
    "popular": false
  },
  {
    "code": "BWP",
    "name": "博茨瓦纳普拉",
    "popular": false
  },
  {
    "code": "CAD",
    "name": "加拿大元",
    "popular": false
  },
  {
    "code": "CHF",
    "name": "瑞士法郎",
    "popular": false
  },
  {
    "code": "CLP",
    "name": "智利比索",
    "popular": false
  },
  {
    "code": "CNY",
    "name": "人民币",
    "popular": false
  },
  {
    "code": "COP",
    "name": "哥伦比亚比索",
    "popular": false
  },
  {
    "code": "CRC",
    "name": "哥斯达黎加科朗",
    "popular": false
  },
  {
    "code": "CVE",
    "name": "佛得角埃斯库多",
    "popular": false
  },
  {
    "code": "CZK",
    "name": "捷克克朗",
    "popular": false
  },
  {
    "code": "DKK",
    "name": "丹麦克朗",
    "popular": false
  },
  {
    "code": "DOP",
    "name": "多米尼加比索",
    "popular": false
  },
  {
    "code": "DZD",
    "name": "阿尔及利亚第纳尔",
    "popular": false
  },
  {
    "code": "EGP",
    "name": "埃及镑",
    "popular": false
  },
  {
    "code": "ETB",
    "name": "埃塞俄比亚比尔",
    "popular": false
  },
  {
    "code": "FJD",
    "name": "斐济元",
    "popular": false
  },
  {
    "code": "GEL",
    "name": "格鲁吉亚拉里",
    "popular": false
  },
  {
    "code": "GHS",
    "name": "加纳塞地",
    "popular": false
  },
  {
    "code": "GMD",
    "name": "冈比亚达拉西",
    "popular": false
  },
  {
    "code": "GNF",
    "name": "几内亚法郎",
    "popular": false
  },
  {
    "code": "GTQ",
    "name": "危地马拉格查尔",
    "popular": false
  },
  {
    "code": "GYD",
    "name": "圭亚那元",
    "popular": false
  },
  {
    "code": "HKD",
    "name": "港币",
    "popular": false
  },
  {
    "code": "HNL",
    "name": "洪都拉斯伦皮拉",
    "popular": false
  },
  {
    "code": "HTG",
    "name": "海地古德",
    "popular": false
  },
  {
    "code": "HUF",
    "name": "匈牙利福林",
    "popular": false
  },
  {
    "code": "IDR",
    "name": "印尼盾",
    "popular": false
  },
  {
    "code": "ILS",
    "name": "以色列新谢克尔",
    "popular": false
  },
  {
    "code": "INR",
    "name": "印度卢比",
    "popular": false
  },
  {
    "code": "ISK",
    "name": "冰岛克朗",
    "popular": false
  },
  {
    "code": "JMD",
    "name": "牙买加元",
    "popular": false
  },
  {
    "code": "JPY",
    "name": "日元",
    "popular": false
  },
  {
    "code": "KES",
    "name": "肯尼亚先令",
    "popular": false
  },
  {
    "code": "KGS",
    "name": "吉尔吉斯斯坦索姆",
    "popular": false
  },
  {
    "code": "KHR",
    "name": "柬埔寨瑞尔",
    "popular": false
  },
  {
    "code": "KRW",
    "name": "韩元",
    "popular": false
  },
  {
    "code": "KWD",
    "name": "科威特第纳尔",
    "popular": false
  },
  {
    "code": "KYD",
    "name": "开曼元",
    "popular": false
  },
  {
    "code": "LAK",
    "name": "老挝基普",
    "popular": false
  },
  {
    "code": "LKR",
    "name": "斯里兰卡卢比",
    "popular": false
  },
  {
    "code": "LSL",
    "name": "莱索托洛蒂",
    "popular": false
  },
  {
    "code": "MAD",
    "name": "摩洛哥迪拉姆",
    "popular": false
  },
  {
    "code": "MNT",
    "name": "蒙古图格里克",
    "popular": false
  },
  {
    "code": "MOP",
    "name": "澳门元",
    "popular": false
  },
  {
    "code": "MUR",
    "name": "毛里求斯卢比",
    "popular": false
  },
  {
    "code": "MVR",
    "name": "马尔代夫拉菲亚",
    "popular": false
  },
  {
    "code": "MWK",
    "name": "马拉维克瓦查",
    "popular": false
  },
  {
    "code": "MXN",
    "name": "墨西哥比索",
    "popular": false
  },
  {
    "code": "MYR",
    "name": "马来西亚林吉特",
    "popular": false
  },
  {
    "code": "MZN",
    "name": "莫桑比克梅蒂卡尔",
    "popular": false
  },
  {
    "code": "NAD",
    "name": "纳米比亚元",
    "popular": false
  },
  {
    "code": "NGN",
    "name": "尼日利亚奈拉",
    "popular": false
  },
  {
    "code": "NIO",
    "name": "尼加拉瓜科多巴",
    "popular": false
  },
  {
    "code": "NOK",
    "name": "挪威克朗",
    "popular": false
  },
  {
    "code": "NPR",
    "name": "尼泊尔卢比",
    "popular": false
  },
  {
    "code": "NZD",
    "name": "新西兰元",
    "popular": false
  },
  {
    "code": "OMR",
    "name": "阿曼里亚尔",
    "popular": false
  },
  {
    "code": "PEN",
    "name": "秘鲁索尔",
    "popular": false
  },
  {
    "code": "PGK",
    "name": "巴布亚新几内亚基那",
    "popular": false
  },
  {
    "code": "PHP",
    "name": "菲律宾比索",
    "popular": false
  },
  {
    "code": "PKR",
    "name": "巴基斯坦卢比",
    "popular": false
  },
  {
    "code": "PLN",
    "name": "波兰兹罗提",
    "popular": false
  },
  {
    "code": "PYG",
    "name": "巴拉圭瓜拉尼",
    "popular": false
  },
  {
    "code": "QAR",
    "name": "卡塔尔里亚尔",
    "popular": false
  },
  {
    "code": "RON",
    "name": "罗马尼亚列伊",
    "popular": false
  },
  {
    "code": "RSD",
    "name": "塞尔维亚第纳尔",
    "popular": false
  },
  {
    "code": "RWF",
    "name": "卢旺达法郎",
    "popular": false
  },
  {
    "code": "SAR",
    "name": "沙特里亚尔",
    "popular": false
  },
  {
    "code": "SBD",
    "name": "所罗门群岛元",
    "popular": false
  },
  {
    "code": "SCR",
    "name": "塞舌尔卢比",
    "popular": false
  },
  {
    "code": "SEK",
    "name": "瑞典克朗",
    "popular": false
  },
  {
    "code": "SGD",
    "name": "新加坡元",
    "popular": false
  },
  {
    "code": "SRD",
    "name": "苏里南元",
    "popular": false
  },
  {
    "code": "THB",
    "name": "泰铢",
    "popular": false
  },
  {
    "code": "TND",
    "name": "突尼斯第纳尔",
    "popular": false
  },
  {
    "code": "TOP",
    "name": "汤加潘加",
    "popular": false
  },
  {
    "code": "TRY",
    "name": "土耳其里拉",
    "popular": false
  },
  {
    "code": "TTD",
    "name": "特立尼达和多巴哥元",
    "popular": false
  },
  {
    "code": "TZS",
    "name": "坦桑尼亚先令",
    "popular": false
  },
  {
    "code": "UAH",
    "name": "乌克兰格里夫纳",
    "popular": false
  },
  {
    "code": "UGX",
    "name": "乌干达先令",
    "popular": false
  },
  {
    "code": "UYU",
    "name": "乌拉圭比索",
    "popular": false
  },
  {
    "code": "VND",
    "name": "越南盾",
    "popular": false
  },
  {
    "code": "VUV",
    "name": "瓦努阿图瓦图",
    "popular": false
  },
  {
    "code": "WST",
    "name": "萨摩亚塔拉",
    "popular": false
  },
  {
    "code": "ZAR",
    "name": "南非兰特",
    "popular": false
  },
  {
    "code": "ZMW",
    "name": "赞比亚克瓦查",
    "popular": false
  }
] as const

export const wiseTargetCurrenciesBySource: Record<string, { codes: string[]; popular: string[] }> = {
  "EUR": {
    "codes": [
      "GBP",
      "INR",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "EUR",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "GBP",
      "INR",
      "USD"
    ]
  },
  "GBP": {
    "codes": [
      "EUR",
      "INR",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GBP",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "INR",
      "USD"
    ]
  },
  "USD": {
    "codes": [
      "EUR",
      "GBP",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "INR"
    ]
  },
  "AED": {
    "codes": [
      "EUR",
      "GBP",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "USD"
    ]
  },
  "ARS": {
    "codes": [
      "ARS"
    ],
    "popular": []
  },
  "AUD": {
    "codes": [
      "EUR",
      "GBP",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "INR"
    ]
  },
  "BRL": {
    "codes": [
      "EUR",
      "USD",
      "AUD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "EGP",
      "FJD",
      "GBP",
      "GEL",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KRW",
      "KYD",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NGN",
      "NOK",
      "NPR",
      "NZD",
      "PEN",
      "PGK",
      "PHP",
      "PLN",
      "PYG",
      "RON",
      "RSD",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "AUD"
    ]
  },
  "CAD": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "CHF": {
    "codes": [
      "EUR",
      "GBP",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "INR"
    ]
  },
  "CLP": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "CNY": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "CZK": {
    "codes": [
      "EUR",
      "GBP",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "INR"
    ]
  },
  "DKK": {
    "codes": [
      "INR",
      "EUR",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "INR",
      "EUR",
      "GBP"
    ]
  },
  "GEL": {
    "codes": [
      "GEL"
    ],
    "popular": []
  },
  "HKD": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "HUF": {
    "codes": [
      "EUR",
      "GBP",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "USD"
    ]
  },
  "IDR": {
    "codes": [
      "EUR",
      "USD",
      "AUD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GBP",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "AUD"
    ]
  },
  "ILS": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "INR": {
    "codes": [
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "EUR",
      "FJD",
      "GBP",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KGS",
      "KHR",
      "KRW",
      "KYD",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NZD",
      "OMR",
      "PEN",
      "PHP",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "AED",
      "ALL",
      "AMD"
    ]
  },
  "JPY": {
    "codes": [
      "USD",
      "GBP",
      "EUR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "USD",
      "GBP",
      "EUR"
    ]
  },
  "MXN": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "MYR": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "NOK": {
    "codes": [
      "INR",
      "PHP",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "EUR",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "INR",
      "PHP",
      "GBP"
    ]
  },
  "NZD": {
    "codes": [
      "GBP",
      "EUR",
      "AUD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "GBP",
      "EUR",
      "AUD"
    ]
  },
  "PHP": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "PLN": {
    "codes": [
      "GBP",
      "EUR",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "GBP",
      "EUR",
      "INR"
    ]
  },
  "RON": {
    "codes": [
      "EUR",
      "USD",
      "INR",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GBP",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "INR"
    ]
  },
  "SEK": {
    "codes": [
      "INR",
      "GBP",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "EUR",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "INR",
      "GBP",
      "USD"
    ]
  },
  "SGD": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "THB": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  },
  "TRY": {
    "codes": [
      "EUR",
      "GBP",
      "USD",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "GBP",
      "USD"
    ]
  },
  "UAH": {
    "codes": [
      "EUR",
      "USD",
      "GBP",
      "AED",
      "ALL",
      "AMD",
      "ARS",
      "AUD",
      "AZN",
      "BBD",
      "BDT",
      "BHD",
      "BMD",
      "BND",
      "BOB",
      "BRL",
      "BSD",
      "BWP",
      "CAD",
      "CHF",
      "CLP",
      "CNY",
      "COP",
      "CRC",
      "CVE",
      "CZK",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ETB",
      "FJD",
      "GEL",
      "GHS",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "ISK",
      "JMD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KRW",
      "KWD",
      "KYD",
      "LAK",
      "LKR",
      "LSL",
      "MAD",
      "MNT",
      "MOP",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SEK",
      "SGD",
      "SRD",
      "THB",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TZS",
      "UAH",
      "UGX",
      "UYU",
      "VND",
      "VUV",
      "WST",
      "ZAR",
      "ZMW"
    ],
    "popular": [
      "EUR",
      "USD",
      "GBP"
    ]
  }
}

export const wiseCountryCurrencies: Record<string, string> = {
  "al": "ALL",
  "dz": "DZD",
  "af": "AFN",
  "ar": "ARS",
  "ae": "AED",
  "aw": "AWG",
  "om": "OMR",
  "az": "AZN",
  "eg": "EGP",
  "et": "ETB",
  "ie": "EUR",
  "ee": "EUR",
  "ad": "EUR",
  "ao": "AOA",
  "ai": "XCD",
  "ag": "XCD",
  "at": "EUR",
  "ax": "EUR",
  "au": "AUD",
  "bb": "BBD",
  "pg": "PGK",
  "bs": "BSD",
  "pk": "PKR",
  "py": "PYG",
  "ps": "ILS",
  "bh": "BHD",
  "pa": "PAB",
  "br": "BRL",
  "by": "BYN",
  "bm": "BMD",
  "bg": "EUR",
  "mp": "USD",
  "mk": "MKD",
  "bj": "XOF",
  "be": "EUR",
  "is": "ISK",
  "bo": "BOB",
  "pr": "USD",
  "pl": "PLN",
  "ba": "BAM",
  "bw": "BWP",
  "bq": "USD",
  "bz": "BZD",
  "bt": "BTN",
  "bf": "XOF",
  "bi": "BIF",
  "bv": "NOK",
  "kp": "KPW",
  "gq": "XAF",
  "dk": "DKK",
  "de": "EUR",
  "tl": "USD",
  "tg": "XOF",
  "do": "DOP",
  "dm": "XCD",
  "ru": "RUB",
  "ec": "USD",
  "er": "ERN",
  "fr": "EUR",
  "fo": "DKK",
  "pf": "XPF",
  "gf": "EUR",
  "tf": "EUR",
  "mf": "EUR",
  "ph": "PHP",
  "fi": "EUR",
  "cv": "CVE",
  "fk": "FKP",
  "gm": "GMD",
  "cg": "XAF",
  "cd": "CDF",
  "co": "COP",
  "cr": "CRC",
  "gd": "XCD",
  "gl": "DKK",
  "ge": "GEL",
  "gg": "GBP",
  "cu": "CUP",
  "gp": "EUR",
  "gu": "USD",
  "gy": "GYD",
  "kz": "KZT",
  "ht": "HTG",
  "kr": "KRW",
  "nl": "EUR",
  "sx": "ANG",
  "hm": "AUD",
  "me": "EUR",
  "hn": "HNL",
  "ki": "AUD",
  "dj": "DJF",
  "kg": "KGS",
  "gn": "GNF",
  "gw": "XOF",
  "ca": "CAD",
  "gh": "GHS",
  "ga": "XAF",
  "kh": "KHR",
  "cz": "CZK",
  "zw": "ZWL",
  "cm": "XAF",
  "qa": "QAR",
  "ky": "KYD",
  "cc": "AUD",
  "km": "KMF",
  "xk": "EUR",
  "ci": "XOF",
  "kw": "KWD",
  "hr": "EUR",
  "ke": "KES",
  "ck": "NZD",
  "cw": "ANG",
  "lv": "EUR",
  "ls": "LSL",
  "la": "LAK",
  "lb": "LBP",
  "lr": "LRD",
  "ly": "LYD",
  "lt": "EUR",
  "li": "CHF",
  "re": "EUR",
  "lu": "EUR",
  "rw": "RWF",
  "ro": "RON",
  "mg": "MGA",
  "im": "GBP",
  "mt": "EUR",
  "mv": "MVR",
  "mw": "MWK",
  "my": "MYR",
  "ml": "XOF",
  "mh": "USD",
  "mq": "EUR",
  "yt": "EUR",
  "mu": "MUR",
  "mr": "MRU",
  "us": "USD",
  "um": "USD",
  "as": "USD",
  "vi": "USD",
  "mn": "MNT",
  "ms": "XCD",
  "bd": "BDT",
  "pe": "PEN",
  "fm": "USD",
  "mm": "MMK",
  "md": "MDL",
  "ma": "MAD",
  "mc": "EUR",
  "mz": "MZN",
  "mx": "MXN",
  "na": "NAD",
  "za": "ZAR",
  "aq": "USD",
  "gs": "FKP",
  "ss": "SSP",
  "np": "NPR",
  "ni": "NIO",
  "ne": "XOF",
  "ng": "NGN",
  "nu": "NZD",
  "no": "NOK",
  "nf": "AUD",
  "pw": "USD",
  "pn": "NZD",
  "pt": "EUR",
  "jp": "JPY",
  "se": "SEK",
  "ch": "CHF",
  "sv": "USD",
  "ws": "WST",
  "rs": "RSD",
  "sl": "SLL",
  "sn": "XOF",
  "cy": "EUR",
  "sc": "SCR",
  "sa": "SAR",
  "bl": "EUR",
  "cx": "AUD",
  "st": "STN",
  "sh": "SHP",
  "kn": "XCD",
  "lc": "XCD",
  "sm": "EUR",
  "pm": "EUR",
  "vc": "XCD",
  "lk": "LKR",
  "sk": "EUR",
  "si": "EUR",
  "sj": "NOK",
  "sz": "SZL",
  "sd": "SDG",
  "sr": "SRD",
  "so": "SOS",
  "sb": "SBD",
  "tj": "TJS",
  "th": "THB",
  "tz": "TZS",
  "to": "TOP",
  "tc": "USD",
  "tt": "TTD",
  "tn": "TND",
  "tv": "AUD",
  "tr": "TRY",
  "tm": "TMT",
  "tk": "NZD",
  "wf": "XPF",
  "vu": "VUV",
  "gt": "GTQ",
  "ve": "VEF",
  "bn": "BND",
  "ug": "UGX",
  "ua": "UAH",
  "uy": "UYU",
  "uz": "UZS",
  "es": "EUR",
  "eh": "MAD",
  "gr": "EUR",
  "sg": "SGD",
  "nc": "XPF",
  "nz": "NZD",
  "hu": "HUF",
  "sy": "SYP",
  "jm": "JMD",
  "am": "AMD",
  "ye": "YER",
  "iq": "IQD",
  "ir": "IRR",
  "il": "ILS",
  "it": "EUR",
  "in": "INR",
  "id": "IDR",
  "gb": "GBP",
  "vg": "USD",
  "io": "USD",
  "jo": "JOD",
  "vn": "VND",
  "zm": "ZMW",
  "je": "GBP",
  "td": "XAF",
  "gi": "GIP",
  "cl": "CLP",
  "cf": "XAF",
  "cn": "CNY",
  "mo": "MOP",
  "tw": "TWD",
  "hk": "HKD",
  "nr": "AUD",
  "va": "EUR",
  "fj": "FJD"
}

export interface WiseQuoteProfile {
  rate: number
  fee: number
  targetAmount: number
  dynamic: boolean
  arrival: string | null
}

export const wiseQuoteProfiles: Record<string, WiseQuoteProfile> = {
  "EUR": {
    "rate": 0.109748,
    "fee": 46.98,
    "targetAmount": 1092.32,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "USD": {
    "rate": 0.127549,
    "fee": 54.76,
    "targetAmount": 1268.51,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "GBP": {
    "rate": 0.0942605,
    "fee": 51.15,
    "targetAmount": 937.78,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "AED": {
    "rate": 0.468486,
    "fee": 63.89,
    "targetAmount": 4654.93,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "ALL": {
    "rate": 10.1078,
    "fee": 420.85,
    "targetAmount": 96824.13,
    "dynamic": true,
    "arrival": "9月14日星期一之前"
  },
  "AMD": {
    "rate": 46.3894,
    "fee": 459.5,
    "targetAmount": 442578.07,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "ARS": {
    "rate": 192.216,
    "fee": 180.1,
    "targetAmount": 1887541.9,
    "dynamic": true,
    "arrival": "3 小时内"
  },
  "AUD": {
    "rate": 0.176807,
    "fee": 47.21,
    "targetAmount": 1759.72,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "AZN": {
    "rate": 0.21682,
    "fee": 439.3,
    "targetAmount": 2072.95,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "BBD": {
    "rate": 0.255097,
    "fee": 383.75,
    "targetAmount": 2453.08,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "BDT": {
    "rate": 15.6662,
    "fee": 131.11,
    "targetAmount": 154608,
    "dynamic": true,
    "arrival": "星期二之前"
  },
  "BHD": {
    "rate": 0.0480909,
    "fee": 171.53,
    "targetAmount": 472.66,
    "dynamic": true,
    "arrival": "9月16日之前"
  },
  "BMD": {
    "rate": 0.127549,
    "fee": 382.82,
    "targetAmount": 1226.66,
    "dynamic": true,
    "arrival": "9月14日星期一之前"
  },
  "BND": {
    "rate": 0.161528,
    "fee": 406.97,
    "targetAmount": 1549.54,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "BOB": {
    "rate": 1.59117,
    "fee": 718.1,
    "targetAmount": 14769.08,
    "dynamic": true,
    "arrival": "9月13日星期日之前"
  },
  "BRL": {
    "rate": 0.653833,
    "fee": 103.32,
    "targetAmount": 6470.78,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "BSD": {
    "rate": 0.127549,
    "fee": 413.45,
    "targetAmount": 1222.75,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "BWP": {
    "rate": 1.77892,
    "fee": 244.89,
    "targetAmount": 17353.56,
    "dynamic": true,
    "arrival": "9月10日星期四之前"
  },
  "CAD": {
    "rate": 0.176279,
    "fee": 48.93,
    "targetAmount": 1754.16,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "CHF": {
    "rate": 0.103244,
    "fee": 52.63,
    "targetAmount": 1027.01,
    "dynamic": false,
    "arrival": "40 分钟内"
  },
  "CLP": {
    "rate": 119.326,
    "fee": 92.19,
    "targetAmount": 1182259,
    "dynamic": false,
    "arrival": "9月10日星期四之前"
  },
  "CNY": {
    "rate": 0.856004,
    "fee": 122.06,
    "targetAmount": 8455.56,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "COP": {
    "rate": 399.367,
    "fee": 160.73,
    "targetAmount": 3929479.74,
    "dynamic": false,
    "arrival": "7 小时内"
  },
  "CRC": {
    "rate": 57.4772,
    "fee": 194.2,
    "targetAmount": 563609.93,
    "dynamic": false,
    "arrival": "11 小时内"
  },
  "CVE": {
    "rate": 12.1331,
    "fee": 436.53,
    "targetAmount": 116034.54,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "CZK": {
    "rate": 2.65611,
    "fee": 56.45,
    "targetAmount": 26411.16,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "DKK": {
    "rate": 0.820313,
    "fee": 50,
    "targetAmount": 8162.11,
    "dynamic": false,
    "arrival": "2 小时内"
  },
  "DOP": {
    "rate": 7.51083,
    "fee": 471.41,
    "targetAmount": 71567.62,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "DZD": {
    "rate": 16.9566,
    "fee": 452.17,
    "targetAmount": 161898.73,
    "dynamic": true,
    "arrival": "9月14日星期一之前"
  },
  "EGP": {
    "rate": 6.49222,
    "fee": 154.33,
    "targetAmount": 63920.26,
    "dynamic": false,
    "arrival": "星期三之前"
  },
  "ETB": {
    "rate": 20.5529,
    "fee": 190.93,
    "targetAmount": 201604.83,
    "dynamic": false,
    "arrival": "9月14日星期一之前"
  },
  "FJD": {
    "rate": 0.281844,
    "fee": 464.08,
    "targetAmount": 2687.64,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "GEL": {
    "rate": 0.333157,
    "fee": 157.35,
    "targetAmount": 3279.15,
    "dynamic": false,
    "arrival": "2 小时内"
  },
  "GHS": {
    "rate": 1.45335,
    "fee": 115.27,
    "targetAmount": 14365.97,
    "dynamic": true,
    "arrival": "2 小时内"
  },
  "GMD": {
    "rate": 9.41097,
    "fee": 250.64,
    "targetAmount": 91750.93,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "GNF": {
    "rate": 1119.71,
    "fee": 380.95,
    "targetAmount": 10770546,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "GTQ": {
    "rate": 0.972893,
    "fee": 393.06,
    "targetAmount": 9346.52,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "GYD": {
    "rate": 26.6851,
    "fee": 190.93,
    "targetAmount": 261756.01,
    "dynamic": false,
    "arrival": "9月11日星期五之前"
  },
  "HKD": {
    "rate": 1,
    "fee": 8.97,
    "targetAmount": 9991.03,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "HNL": {
    "rate": 3.43254,
    "fee": 446.66,
    "targetAmount": 32792.22,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "HTG": {
    "rate": 16.6814,
    "fee": 638.49,
    "targetAmount": 156163.09,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "HUF": {
    "rate": 39.873,
    "fee": 65.98,
    "targetAmount": 396099,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "IDR": {
    "rate": 2250.72,
    "fee": 55.67,
    "targetAmount": 22381902,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "ILS": {
    "rate": 0.384087,
    "fee": 71.63,
    "targetAmount": 3813.36,
    "dynamic": false,
    "arrival": "3 小时内"
  },
  "INR": {
    "rate": 12.0644,
    "fee": 60.59,
    "targetAmount": 119913.02,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "ISK": {
    "rate": 15.4525,
    "fee": 214.14,
    "targetAmount": 151216,
    "dynamic": true,
    "arrival": "星期二之前"
  },
  "JMD": {
    "rate": 20.1941,
    "fee": 540.39,
    "targetAmount": 191028.31,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "JPY": {
    "rate": 19.7337,
    "fee": 64.45,
    "targetAmount": 196065,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "KES": {
    "rate": 16.5048,
    "fee": 122.89,
    "targetAmount": 163020,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "KGS": {
    "rate": 11.1587,
    "fee": 403.27,
    "targetAmount": 107087.03,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "KHR": {
    "rate": 516.572,
    "fee": 430.08,
    "targetAmount": 4943552.71,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "KRW": {
    "rate": 172.057,
    "fee": 83.75,
    "targetAmount": 1706160,
    "dynamic": false,
    "arrival": "3 分钟内"
  },
  "KWD": {
    "rate": 0.0391383,
    "fee": 190.93,
    "targetAmount": 383.91,
    "dynamic": false,
    "arrival": "9月15日星期二之前"
  },
  "KYD": {
    "rate": 0.10459,
    "fee": 211.24,
    "targetAmount": 1023.81,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "LAK": {
    "rate": 2860.98,
    "fee": 354.79,
    "targetAmount": 27594753,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "LKR": {
    "rate": 41.8583,
    "fee": 77.69,
    "targetAmount": 415331.03,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "LSL": {
    "rate": 2.04,
    "fee": 406.05,
    "targetAmount": 19571.66,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "MAD": {
    "rate": 1.1984,
    "fee": 230.69,
    "targetAmount": 11707.54,
    "dynamic": false,
    "arrival": "9月10日星期四之前"
  },
  "MNT": {
    "rate": 458.154,
    "fee": 392.12,
    "targetAmount": 4401888.65,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "MOP": {
    "rate": 1.03,
    "fee": 419.94,
    "targetAmount": 9867.46,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "MUR": {
    "rate": 5.98287,
    "fee": 190.93,
    "targetAmount": 58686.39,
    "dynamic": false,
    "arrival": "9月11日星期五之前"
  },
  "MVR": {
    "rate": 1.94278,
    "fee": 190.93,
    "targetAmount": 19056.87,
    "dynamic": false,
    "arrival": "9月15日星期二之前"
  },
  "MWK": {
    "rate": 221.171,
    "fee": 567.34,
    "targetAmount": 2086230.84,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "MXN": {
    "rate": 2.15737,
    "fee": 68.73,
    "targetAmount": 21425.42,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "MYR": {
    "rate": 0.516062,
    "fee": 51.78,
    "targetAmount": 5133.9,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "MZN": {
    "rate": 8.13931,
    "fee": 190.93,
    "targetAmount": 79839.06,
    "dynamic": false,
    "arrival": "9月14日星期一之前"
  },
  "NAD": {
    "rate": 2.03963,
    "fee": 380.95,
    "targetAmount": 19619.3,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "NGN": {
    "rate": 173.93,
    "fee": 69.81,
    "targetAmount": 1727157.95,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "NIO": {
    "rate": 4.6965,
    "fee": 495.12,
    "targetAmount": 44639.67,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "NOK": {
    "rate": 1.18261,
    "fee": 51.2,
    "targetAmount": 11765.55,
    "dynamic": false,
    "arrival": "星期三之前"
  },
  "NPR": {
    "rate": 19.2841,
    "fee": 193.52,
    "targetAmount": 189109,
    "dynamic": true,
    "arrival": "30 分钟内"
  },
  "NZD": {
    "rate": 0.217049,
    "fee": 51.92,
    "targetAmount": 2159.22,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "OMR": {
    "rate": 0.0491062,
    "fee": 163.72,
    "targetAmount": 483.02,
    "dynamic": true,
    "arrival": "星期三之前"
  },
  "PEN": {
    "rate": 0.4279,
    "fee": 190.93,
    "targetAmount": 4197.3,
    "dynamic": false,
    "arrival": "9月11日星期五之前"
  },
  "PGK": {
    "rate": 0.569286,
    "fee": 481.45,
    "targetAmount": 5418.78,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "PHP": {
    "rate": 7.99409,
    "fee": 66.9,
    "targetAmount": 79406.1,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "PKR": {
    "rate": 35.3964,
    "fee": 75.15,
    "targetAmount": 351303.96,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "PLN": {
    "rate": 0.473288,
    "fee": 55.26,
    "targetAmount": 4706.73,
    "dynamic": false,
    "arrival": "星期三之前"
  },
  "PYG": {
    "rate": 759.233,
    "fee": 407.91,
    "targetAmount": 7282631,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "QAR": {
    "rate": 0.464953,
    "fee": 170.55,
    "targetAmount": 4570.23,
    "dynamic": true,
    "arrival": "9月10日星期四之前"
  },
  "RON": {
    "rate": 0.576427,
    "fee": 55.91,
    "targetAmount": 5732.04,
    "dynamic": false,
    "arrival": "星期三之前"
  },
  "RSD": {
    "rate": 12.8792,
    "fee": 216.06,
    "targetAmount": 126009.32,
    "dynamic": true,
    "arrival": "9月10日星期四之前"
  },
  "RWF": {
    "rate": 187.6,
    "fee": 295.42,
    "targetAmount": 1820579,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "SAR": {
    "rate": 0.478983,
    "fee": 163.72,
    "targetAmount": 4711.41,
    "dynamic": true,
    "arrival": "星期三之前"
  },
  "SBD": {
    "rate": 1.0208,
    "fee": 650.82,
    "targetAmount": 9543.64,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "SCR": {
    "rate": 1.79508,
    "fee": 405.12,
    "targetAmount": 17223.58,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "SEK": {
    "rate": 1.22546,
    "fee": 53.34,
    "targetAmount": 12189.23,
    "dynamic": false,
    "arrival": "2 小时内"
  },
  "SGD": {
    "rate": 0.161521,
    "fee": 52.63,
    "targetAmount": 1606.71,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "SRD": {
    "rate": 4.82641,
    "fee": 745.78,
    "targetAmount": 44664.66,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "THB": {
    "rate": 4.19597,
    "fee": 86.3,
    "targetAmount": 41597.59,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "TND": {
    "rate": 0.370765,
    "fee": 293.51,
    "targetAmount": 3598.83,
    "dynamic": true,
    "arrival": "9月17日之前"
  },
  "TOP": {
    "rate": 0.295149,
    "fee": 360.41,
    "targetAmount": 2845.12,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "TRY": {
    "rate": 6.17761,
    "fee": 61.27,
    "targetAmount": 61397.6,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "TTD": {
    "rate": 0.856157,
    "fee": 351.99,
    "targetAmount": 8260.21,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "TZS": {
    "rate": 336.596,
    "fee": 172.79,
    "targetAmount": 3307799.58,
    "dynamic": true,
    "arrival": "星期二之前"
  },
  "UAH": {
    "rate": 5.63765,
    "fee": 79.11,
    "targetAmount": 55930.51,
    "dynamic": true,
    "arrival": null
  },
  "UGX": {
    "rate": 482.111,
    "fee": 172.17,
    "targetAmount": 4738105,
    "dynamic": true,
    "arrival": "9 小时内"
  },
  "UYU": {
    "rate": 5.13447,
    "fee": 225.2,
    "targetAmount": 50188.42,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "VND": {
    "rate": 3325.83,
    "fee": 78.81,
    "targetAmount": 32996191,
    "dynamic": false,
    "arrival": "数秒内"
  },
  "VUV": {
    "rate": 15.0444,
    "fee": 818.51,
    "targetAmount": 138130,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "WST": {
    "rate": 0.345192,
    "fee": 626.99,
    "targetAmount": 3235.49,
    "dynamic": true,
    "arrival": "9月11日星期五之前"
  },
  "ZAR": {
    "rate": 2.03992,
    "fee": 82.13,
    "targetAmount": 20231.66,
    "dynamic": false,
    "arrival": "星期二之前"
  },
  "ZMW": {
    "rate": 2.45469,
    "fee": 468.66,
    "targetAmount": 23396.48,
    "dynamic": true,
    "arrival": "星期三之前"
  }
}
